/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the MIT;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    MIT
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#undef BUILTIN_GENERATOR_LIBICU

#undef BUILTIN_GENERATOR_LIBIDN

#undef BUILTIN_GENERATOR_LIBIDN2

#define HAVE_ALLOCA

#define HAVE_ALLOCA_H

#define HAVE_CLOCK_GETTIME

#define HAVE_DIRENT_H

#define HAVE_FMEMOPEN

#define HAVE_NL_LANGINFO

#define HAVE_STDINT_H

#define HAVE_STRNDUP

#define HAVE_UNISTD_H

#define PACKAGE_VERSION "0.21.1"

#undef WITH_LIBICU

#undef WITH_LIBIDN

#undef WITH_LIBIDN2

