/* Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under MIT (the "License");
 */

/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#undef BUILTIN_GENERATOR_LIBICU

#undef BUILTIN_GENERATOR_LIBIDN

#undef BUILTIN_GENERATOR_LIBIDN2

#define HAVE_ALLOCA

#define HAVE_ALLOCA_H

#define HAVE_CLOCK_GETTIME

#define HAVE_DIRENT_H

#define HAVE_FMEMOPEN

#define HAVE_NL_LANGINFO

#define HAVE_STDINT_H

#define HAVE_STRNDUP

#define HAVE_UNISTD_H

#define PACKAGE_VERSION "0.21.1"

#undef WITH_LIBICU

#undef WITH_LIBIDN

#undef WITH_LIBIDN2

